/**
 * LiftIQ Backend - Type Definitions
 *
 * This module contains shared type definitions used across the backend.
 * Most types are generated by Prisma, but we define additional types here
 * for API contracts and service interfaces.
 */

import { User, Exercise, WorkoutSession, Set, SetType, UnitType } from '@prisma/client';

// ============================================================================
// API Request/Response Types
// ============================================================================

/**
 * Standard API success response
 */
export interface ApiResponse<T> {
  success: true;
  data: T;
  meta?: Record<string, unknown>;
}

/**
 * Standard API error response
 */
export interface ApiError {
  success: false;
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}

/**
 * Pagination parameters
 */
export interface PaginationParams {
  page: number;
  limit: number;
  skip: number;
}

/**
 * Pagination metadata in response
 */
export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

// ============================================================================
// User Types
// ============================================================================

/**
 * User profile data returned to clients
 */
export interface UserProfile {
  id: string;
  email: string;
  displayName: string | null;
  avatarUrl: string | null;
  unitPreference: UnitType;
  onboardingCompleted: boolean;
  createdAt: Date;
}

/**
 * Data required for user registration
 */
export interface RegisterInput {
  firebaseUid: string;
  email: string;
  displayName?: string;
}

/**
 * Data for completing onboarding
 */
export interface OnboardingInput {
  unitPreference: UnitType;
  experienceLevel: string;
  primaryGoal: string;
  privacyPolicyAccepted: boolean;
}

// ============================================================================
// Workout Types
// ============================================================================

/**
 * Input for starting a workout
 */
export interface StartWorkoutInput {
  templateId?: string;
  notes?: string;
}

/**
 * Input for logging a set
 */
export interface LogSetInput {
  exerciseLogId: string;
  weight: number;
  reps: number;
  rpe?: number;
  setType?: SetType;
}

/**
 * Workout summary for list views
 */
export interface WorkoutSummary {
  id: string;
  templateName: string | null;
  startedAt: Date;
  completedAt: Date | null;
  durationSeconds: number | null;
  exerciseCount: number;
  setCount: number;
  prCount: number;
}

// ============================================================================
// Exercise Types
// ============================================================================

/**
 * Exercise list item (minimal data for lists)
 */
export interface ExerciseListItem {
  id: string;
  name: string;
  primaryMuscles: string[];
  equipment: string[];
  category: string | null;
  isCompound: boolean;
  isCustom: boolean;
}

/**
 * Full exercise details
 */
export interface ExerciseDetail extends ExerciseListItem {
  description: string | null;
  instructions: string | null;
  secondaryMuscles: string[];
  formCues: string[];
  commonMistakes: string[];
}

/**
 * Input for creating custom exercise
 */
export interface CreateExerciseInput {
  name: string;
  description?: string;
  instructions?: string;
  primaryMuscles: string[];
  secondaryMuscles?: string[];
  equipment?: string[];
  formCues?: string[];
  commonMistakes?: string[];
  category?: string;
  isCompound?: boolean;
}

// ============================================================================
// Template Types
// ============================================================================

/**
 * Template exercise configuration
 */
export interface TemplateExerciseInput {
  exerciseId: string;
  orderIndex: number;
  defaultSets?: number;
  defaultReps?: number;
  defaultRestSeconds?: number;
  notes?: string;
}

/**
 * Input for creating a template
 */
export interface CreateTemplateInput {
  name: string;
  description?: string;
  estimatedDuration?: number;
  exercises: TemplateExerciseInput[];
}

// ============================================================================
// Progression Types
// ============================================================================

/**
 * Progression suggestion returned by the algorithm
 */
export interface ProgressionSuggestion {
  suggestedWeight: number;
  action: 'INCREASE' | 'MAINTAIN' | 'DECREASE';
  reasoning: string;
  confidence: number;
}

/**
 * Historical data for progression calculation
 */
export interface ExerciseHistory {
  sessionDate: Date;
  weight: number;
  sets: number;
  reps: number[];
  averageRpe: number | null;
}

// ============================================================================
// Analytics Types
// ============================================================================

/**
 * One rep max estimate
 */
export interface OneRepMaxEstimate {
  exerciseId: string;
  exerciseName: string;
  estimated1RM: number;
  date: Date;
  formula: string;
}

/**
 * Volume data for a muscle group
 */
export interface MuscleVolumeData {
  muscle: string;
  sets: number;
  volume: number;
  periodStart: Date;
  periodEnd: Date;
}

/**
 * Workout consistency data
 */
export interface ConsistencyData {
  date: Date;
  worked: boolean;
  workoutId?: string;
}

// ============================================================================
// AI/Chat Types
// ============================================================================

/**
 * Chat message in conversation
 */
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
}

/**
 * Context provided to AI for personalization
 */
export interface AIContext {
  userId: string;
  recentWorkouts: WorkoutSummary[];
  currentProgram?: string;
  goals?: string;
  exerciseHistory?: Record<string, ExerciseHistory[]>;
}
