export type ApiSuccess<T> = {
  success: true;
  data: T;
};

export type ApiError = {
  success: false;
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

export type Readiness = {
  sleep: number;
  energy: number;
  soreness: number;
};

export type UserSettings = {
  advancedTracking: { enabled: boolean; rpe: boolean; tempo: boolean; readiness: boolean };
  plates: { kg: number[]; lb: number[] };
  barWeights: { barbell: number; ezBar: number; trapBar: number };
  rest: { workingSeconds: number; warmupSeconds: number; autoStart: boolean };
  cardio: { weeklyMinutesGoal: number; defaultDistanceUnit: "km" | "mi" };
  previousValueScope: "slot" | "anywhere";
};

export type UserSettingsUpdate = {
  advancedTracking?: Partial<UserSettings["advancedTracking"]>;
  plates?: Partial<UserSettings["plates"]>;
  barWeights?: Partial<UserSettings["barWeights"]>;
  rest?: Partial<UserSettings["rest"]>;
  cardio?: Partial<UserSettings["cardio"]>;
  previousValueScope?: UserSettings["previousValueScope"];
};

export type User = {
  id: string;
  email: string;
  displayName: string;
  preferredUnit: "kg" | "lb";
  gender: "MALE" | "FEMALE" | "NON_BINARY" | "PREFER_NOT_TO_SAY";
  xpTotal: number;
  level: number;
  settings: UserSettings;
  selectedTitleKey?: string | null;
  selectedTitleLabel?: string | null;
  selectedBadgeKey?: string | null;
  selectedBadgeLabel?: string | null;
  selectedBadgeIconKey?: string | null;
  avatarConfig: Record<string, unknown> | null;
};

export type SocialUser = {
  id: string;
  email: string;
  displayName: string;
  level: number;
  xpTotal: number;
  selectedTitleLabel?: string | null;
  selectedBadgeLabel?: string | null;
  selectedBadgeIconKey?: string | null;
  isFollowing: boolean;
};

export type Exercise = {
  id: string;
  name: string;
  exerciseCategory: "STRENGTH" | "CARDIO";
  equipmentType: string;
  machineType: string | null;
  attachment: string | null;
  loadType:
    | "BODYWEIGHT"
    | "ASSISTED_BODYWEIGHT"
    | "EXTERNAL"
    | "FIXED_WEIGHT"
    | "PLATE_TOTAL"
    | "STACK"
    | "CABLE_STACK";
  unitMode: "kg" | "lb";
  primaryMuscles: string[];
  secondaryMuscles: string[];
  isSystem: boolean;
};

export type ExerciseSubstitutes = {
  sourceExercise: Exercise;
  equivalents: Exercise[];
  alternatives: Exercise[];
};

export type LoadType = Exercise["loadType"];

export type ExerciseCategory = Exercise["exerciseCategory"];

export type TrackingMode =
  | "ABSOLUTE_WEIGHT"
  | "PLATES_PER_SIDE"
  | "PLATES_TOTAL"
  | "BODYWEIGHT_ONLY"
  | "BODYWEIGHT_PLUS_LOAD"
  | "BAND_LEVEL"
  | "PER_SIDE_LOAD"
  | "CARDIO";

export type UserExercisePreference = {
  id: string;
  exerciseId: string;
  unilateral: boolean | null;
  trackingMode: TrackingMode | null;
  barWeight: number | null;
  restSeconds: number | null;
};

export type ProgressionSlotInfo = {
  programWorkoutExerciseId: string;
  status: "FORMATIVE" | "ACTIVE" | "DELOADED";
  workingWeight: number | null;
  suggestedWeight: number | null;
  suggestionReason: string | null;
  successStreak: number;
  failStreak: number;
  lastEvaluatedAt: string | null;
};

export type ProgramProgression = {
  currentWeek: number;
  formativeWeek: boolean;
  tracks: ProgressionSlotInfo[];
};

export type PreviousSetEntry = {
  setNumber: number;
  weight: number | null;
  reps: number;
  rpe: number | null;
  setType: WorkoutSetType;
  isWorkingSet: boolean;
  trackingData: WorkoutSetTrackingData | null;
};

export type PreviousSets = {
  completedAt: string;
  sets: PreviousSetEntry[];
};

export type PreviousSetsResponse = {
  byExercise: Record<string, PreviousSets>;
  bySlot: Record<string, PreviousSets>;
};

export type WorkoutSetType =
  | "NORMAL"
  | "WARMUP"
  | "AMRAP"
  | "DROP"
  | "CLUSTER"
  | "SUPERSET"
  | "CARDIO";

export type WorkoutSetTrackingData = {
  unilateral?: boolean | null;
  leftWeight?: number | null;
  rightWeight?: number | null;
  leftReps?: number | null;
  rightReps?: number | null;
  leftRpe?: number | null;
  rightRpe?: number | null;
  plateCount?: number | null;
  plateWeight?: number | null;
  barWeight?: number | null;
  externalLoad?: number | null;
  bandLevel?: string | null;
  perSideLoad?: number | null;
  durationSeconds?: number | null;
  distance?: number | null;
  distanceUnit?: string | null;
  incline?: number | null;
  resistance?: number | null;
  speed?: number | null;
  clusterSize?: number | null;
  clusterPattern?: string | null;
  tempo?: string | null;
  generatedFromSetNumber?: number | null;
  dropPhase?: number | null;
  dropPercent?: number | null;
  dropGroupId?: string | null;
  autoGenerated?: boolean | null;
};

export type ProgramExercise = {
  id: string;
  exerciseId: string;
  orderIndex: number;
  sets: number;
  repMin: number;
  repMax: number;
  restSeconds: number;
  startWeight: number | null;
  increment: number;
  deloadFactor: number;
  targetRpe: number | null;
  loadTypeOverride: Exercise["loadType"] | null;
  trackingMode: TrackingMode | null;
  defaultTrackingData: WorkoutSetTrackingData | null;
  machineOverride: string | null;
  attachmentOverride: string | null;
  unilateral: boolean;
  notes: string | null;
  exercise: Exercise;
};

export type ProgramWorkout = {
  id: string;
  dayLabel: string;
  title: string;
  orderIndex: number;
  estimatedMinutes: number;
  xpReward: number;
  exercises: ProgramExercise[];
};

export type ProgramWeek = {
  id: string;
  weekNumber: number;
  label: string;
  isDeload: boolean;
  workouts: ProgramWorkout[];
};

export type Program = {
  id: string;
  isSystem: boolean;
  name: string;
  goal: string;
  description: string | null;
  status: "ACTIVE" | "PAUSED" | "COMPLETED" | "ARCHIVED";
  currentWeek: number;
  adherenceStreak: number;
  allowCopy: boolean;
  weeks: ProgramWeek[];
};

export type ProgramDifficulty = "Beginner" | "Intermediate" | "Advanced";
export type ProgramGoal =
  | "Strength"
  | "Hypertrophy"
  | "General Fitness"
  | "Powerlifting";

export type TemplateExercise = {
  id: string;
  exerciseId: string;
  orderIndex: number;
  sets: number;
  repMin: number;
  repMax: number;
  restSeconds: number;
  startWeight: number | null;
  loadTypeOverride: LoadType | null;
  trackingMode: TrackingMode | null;
  defaultTrackingData: WorkoutSetTrackingData | null;
  machineOverride: string | null;
  attachmentOverride: string | null;
  unilateral: boolean;
  notes: string | null;
  exercise: Exercise;
};

export type WorkoutTemplate = {
  id: string;
  isSystem: boolean;
  name: string;
  description: string | null;
  exercises: TemplateExercise[];
};

export type DraftExercise = {
  exerciseId: string;
  exerciseName?: string;
  exerciseCategory?: ExerciseCategory;
  sets: number;
  repMin: number;
  repMax: number;
  restSeconds?: number;
  startWeight?: number | null;
  increment?: number;
  deloadFactor?: number;
  targetRpe?: number | null;
  loadTypeOverride?: LoadType | null;
  trackingMode?: TrackingMode | null;
  defaultTrackingData?: WorkoutSetTrackingData | null;
  machineOverride?: string | null;
  attachmentOverride?: string | null;
  unilateral?: boolean;
  notes?: string | null;
};

export type DraftTemplateDay = {
  templateId?: string;
  dayLabel: string;
  title: string;
  description?: string;
  estimatedMinutes?: number;
  exercises: DraftExercise[];
};

export type CreateProgramInput = {
  name: string;
  goal: ProgramGoal;
  description?: string;
  durationWeeks: number;
  daysPerWeek: number;
  days: DraftTemplateDay[];
};

export type ProgramDraft = {
  name: string;
  goal: ProgramGoal;
  description: string;
  durationWeeks: number;
  daysPerWeek: number;
  difficulty: ProgramDifficulty;
  days: DraftTemplateDay[];
};

export type TemplateDraft = {
  name: string;
  description: string;
  estimatedMinutes: number;
  exercises: DraftExercise[];
};

export type ProgressionRecommendation = {
  state: "START" | "HOLD" | "INCREASE" | "DELOAD";
  weight: number | null;
  reason: string;
};

export type ActiveProgram = Program & {
  currentWeek: ProgramWeek | undefined;
  currentWeekTotal: number;
  currentWeekCompleted: number;
  currentWeekSkipped: number;
  currentWeekCompletion: number;
  completedWorkoutIds: string[];
  skippedWorkoutIds: string[];
  graceHours: number;
  recommendations: Record<string, ProgressionRecommendation>;
};

export type WorkoutSession = {
  id: string;
  title: string;
  entryType: "PROGRAM" | "TEMPLATE" | "QUICK";
  status: "DRAFT" | "IN_PROGRESS" | "COMPLETED";
  wasPlanned: boolean;
  totalXp: number;
  notes: string | null;
  savedDraft: WorkoutDraft | null;
  originDraft: WorkoutDraft | null;
  startedAt: string;
  pausedAt: string | null;
  accumulatedPauseSeconds: number;
  totalDurationSeconds: number | null;
  completedAt: string | null;
  programWorkoutId: string | null;
  templateId: string | null;
  inviteId: string | null;
};

export type WorkoutSetRecord = {
  id: string;
  setNumber: number;
  weight: number | null;
  reps: number;
  rpe: number | null;
  setType: WorkoutSetType;
  trackingData: WorkoutSetTrackingData | null;
  isWorkingSet: boolean;
  isPersonalRecord: boolean;
};

export type WorkoutExerciseRecord = {
  id: string;
  exerciseId: string | null;
  exerciseName: string;
  exerciseCategory: ExerciseCategory;
  equipmentType: string;
  machineType: string | null;
  attachment: string | null;
  loadType: Exercise["loadType"];
  trackingMode: TrackingMode | null;
  defaultTrackingData: WorkoutSetTrackingData | null;
  unitMode: "kg" | "lb";
  unilateral: boolean;
  orderIndex: number;
  notes: string | null;
  prescribedSetCount: number | null;
  repMin: number | null;
  repMax: number | null;
  suggestedWeight: number | null;
  sourceProgramExerciseId: string | null;
  substitutedFromExerciseId: string | null;
  substitutedFromExerciseName: string | null;
  substitutionMode: "EQUIVALENT" | "ALTERNATE" | null;
  countsForProgression: boolean;
  supersetGroupId: string | null;
  supersetPosition: number | null;
  sets: WorkoutSetRecord[];
};

export type WorkoutExerciseReview = {
  workoutExerciseId: string;
  volume: number;
  bestSetLabel: string;
  estimatedOneRepMax: number | null;
  personalRecordSets: number;
  previousVolume: number | null;
  previousBestSetLabel: string | null;
  previousEstimatedOneRepMax: number | null;
  volumeChange: number | null;
  oneRepMaxChange: number | null;
};

export type WorkoutSessionDetail = WorkoutSession & {
  exercises: WorkoutExerciseRecord[];
  exerciseReviews: WorkoutExerciseReview[];
};

export type WorkoutDraftSet = {
  setNumber: number;
  weight: number | null;
  reps: number;
  rpe: number | null;
  completed?: boolean;
  setType?: WorkoutSetType;
  trackingData?: WorkoutSetTrackingData | null;
  isWorkingSet?: boolean;
};

export type WorkoutDraftExercise = {
  /** Client-only stable identity for list reordering; stripped by the server. */
  clientKey?: string;
  exerciseId: string | null;
  exerciseName: string;
  exerciseCategory: ExerciseCategory;
  equipmentType: string;
  machineType?: string | null;
  attachment?: string | null;
  loadType: Exercise["loadType"];
  trackingMode: TrackingMode;
  defaultTrackingData?: WorkoutSetTrackingData | null;
  unitMode: "kg" | "lb";
  unilateral?: boolean;
  notes?: string;
  prescribedSetCount?: number | null;
  /** Per-exercise rest override in seconds; null/undefined falls back to global settings. */
  restSeconds?: number | null;
  repMin?: number | null;
  repMax?: number | null;
  suggestedWeight?: number | null;
  recommendationReason?: string | null;
  sourceProgramExerciseId?: string | null;
  substitutedFromExerciseId?: string | null;
  substitutedFromExerciseName?: string | null;
  substitutionMode?: "EQUIVALENT" | "ALTERNATE" | null;
  countsForProgression?: boolean;
  supersetGroupId?: string | null;
  supersetPosition?: number | null;
  sets: WorkoutDraftSet[];
};

export type CreateExerciseInput = {
  name: string;
  exerciseCategory?: ExerciseCategory;
  equipmentType: string;
  machineType?: string;
  attachment?: string;
  loadType: LoadType;
  primaryMuscles: string[];
  secondaryMuscles?: string[];
};

export type CreateTemplateInput = {
  name: string;
  description?: string;
  exercises: DraftExercise[];
};

export type WorkoutDraft = {
  title: string;
  notes?: string;
  formativeWeek?: boolean;
  exercises: WorkoutDraftExercise[];
};

export type LeaderboardEntry = {
  rank: number;
  userId: string;
  displayName: string;
  level: number;
  xp: number;
  selectedTitleLabel?: string | null;
  selectedBadgeLabel?: string | null;
  selectedBadgeIconKey?: string | null;
};

export type Challenge = {
  id: string;
  key: string;
  title: string;
  description: string;
  joined: boolean;
  myScore: number;
  target: number | null;
  metric: "XP" | "WORKOUTS" | "PROGRAM_WEEKS" | "PRS";
  periodEnd: string;
};

export type ReactionSummary = {
  emoji: string;
  count: number;
  userReacted: boolean;
};

export type ActivityEvent = {
  id: string;
  title: string;
  body: string | null;
  createdAt: string;
  type: string;
  user: Pick<User, "id" | "displayName" | "level">;
  reactions: ReactionSummary[];
};

export type ChallengeCategory =
  | "CONSISTENCY"
  | "STRENGTH"
  | "PROGRESSION"
  | "PROGRAMS"
  | "SOCIAL";

export type ChallengeRank =
  | "ROOKIE"
  | "REGULAR"
  | "DEDICATED"
  | "SERIOUS"
  | "SAVAGE"
  | "TITAN"
  | "GOD";

export type ChallengeTierReward = {
  key: string;
  label: string;
};

export type ChallengeTier = {
  id: string;
  rank: ChallengeRank;
  threshold: number;
  femaleThreshold?: number | null;
  xpReward: number;
  unlocked: boolean;
  unlockedAt: string | null;
  titleRewardKey: string | null;
  titleRewardLabel: string | null;
  badgeRewardKey: string | null;
  badgeRewardLabel: string | null;
  badgeRewardIconKey?: string | null;
};

export type ChallengeFamily = {
  id: string;
  key: string;
  category: ChallengeCategory;
  categoryLabel: string;
  iconKey: string;
  title: string;
  description: string;
  unitSingular: string;
  unitPlural: string;
  progress: number;
  currentRank: ChallengeRank | null;
  nextTier:
    | {
        id: string;
        rank: ChallengeRank;
        threshold: number;
        xpReward: number;
        remaining: number;
        titleRewardKey: string | null;
        titleRewardLabel: string | null;
        badgeRewardKey: string | null;
        badgeRewardLabel: string | null;
        badgeRewardIconKey?: string | null;
      }
    | null;
  tiers: ChallengeTier[];
};

export type ChallengeCategorySection = {
  key: ChallengeCategory;
  label: string;
  families: ChallengeFamily[];
};

export type ChallengeUnlock = {
  familyId: string;
  familyKey: string;
  familyTitle: string;
  iconKey: string;
  rank: ChallengeRank;
  threshold: number;
  xpReward: number;
  unlockedAt: string;
  titleRewardKey: string | null;
  titleRewardLabel: string | null;
  badgeRewardKey: string | null;
  badgeRewardLabel: string | null;
};

export type ChallengeRewardItem = {
  key: string;
  label: string;
  iconKey?: string | null;
  familyKey: string;
  familyTitle: string;
  rank: ChallengeRank;
  unlockedAt: string;
};

export type ChallengeLibrary = {
  categories: ChallengeCategorySection[];
  summary: {
    unlockedTierCount: number;
    totalTierCount: number;
    unlockedFamilyCount: number;
    totalFamilyCount: number;
    unlockedTitles: ChallengeRewardItem[];
    unlockedBadges: ChallengeRewardItem[];
  };
};

export type ProgressWeeklyExercise = {
  exerciseId: string;
  exerciseName: string;
  volume: number;
  sessions: number;
};

export type ProgressWeeklyMuscle = {
  muscle: string;
  volume: number;
};

export type ProgressWeeklySummary = {
  startDate: string;
  endDate: string;
  sessionsCompleted: number;
  plannedSessionsCompleted: number;
  unplannedSessionsCompleted: number;
  xpEarned: number;
  totalVolume: number;
  topExercises: ProgressWeeklyExercise[];
  topMuscleGroups: ProgressWeeklyMuscle[];
};

export type ProgressActiveProgramSummary = {
  programId: string;
  name: string;
  currentWeek: number;
  completed: number;
  total: number;
  completion: number;
} | null;

export type ProgressRecentPr = {
  setId: string;
  workoutId: string;
  workoutTitle: string;
  exerciseId: string | null;
  exerciseName: string;
  bestSetLabel: string;
  estimatedOneRepMax: number | null;
  previousBest: number | null;
  improvement: number | null;
  completedAt: string;
};

export type ProgressExerciseTrend = {
  exerciseId: string;
  exerciseName: string;
  equipmentType: string;
  sessionCount: number;
  totalVolume: number;
  latestEstimatedOneRepMax: number | null;
  bestEstimatedOneRepMax: number | null;
  recentChange: number | null;
  lastPerformed: string;
  personalRecordCount: number;
};

export type ProgressChallengeSummary = {
  unlockedTierCount: number;
  totalTierCount: number;
  unlockedFamilyCount: number;
  totalFamilyCount: number;
  recentUnlocks: ChallengeUnlock[];
  closestNext: ChallengeFamily[];
};

export type WeeklyVolumePoint = {
  weekStart: string;
  volume: number;
};

export type ProgressOverview = {
  weeklyVolumeSeries: WeeklyVolumePoint[];
  weeklySummary: ProgressWeeklySummary;
  activeProgramSummary: ProgressActiveProgramSummary;
  recentPrs: ProgressRecentPr[];
  exerciseTrends: ProgressExerciseTrend[];
  challengeSummary: ProgressChallengeSummary;
};

export type MonthlyRecapTopExercise = {
  exerciseId: string | null;
  name: string;
  sets: number;
  volume: number;
};

export type MonthlyRecapMuscleVolume = {
  muscle: string;
  volume: number;
};

/** Monthly training recap. All volumes are in kg; format with `formatVolume`. */
export type MonthlyRecap = {
  month: string;
  monthLabel: string;
  sessions: number;
  plannedSessions: number;
  totalVolume: number;
  totalSets: number;
  totalReps: number;
  totalDurationSeconds: number;
  xpEarned: number;
  prCount: number;
  activeDays: number;
  bestWeek: { startDate: string; sessions: number } | null;
  topExercises: MonthlyRecapTopExercise[];
  muscleVolumes: MonthlyRecapMuscleVolume[];
  previousMonth: { sessions: number; totalVolume: number; prCount: number } | null;
};

/** A single training day in the consistency calendar. Volume is in kg. */
export type TrainingCalendarDay = {
  date: string;
  sessions: number;
  volume: number;
  durationSeconds: number;
  xp: number;
  prCount: number;
};

/** Training consistency calendar. Volumes are in kg; format with `formatVolume`. */
export type TrainingCalendar = {
  from: string;
  to: string;
  days: TrainingCalendarDay[];
  totalSessions: number;
  currentStreakDays: number;
  longestStreakDays: number;
};

export type BodyMetricEntry = {
  id: string;
  weight: number | null;
  measurements: Record<string, number> | null;
  note: string | null;
  recordedAt: string;
};

export type BodyMetricsView = {
  preferredUnit: "kg" | "lb";
  entries: BodyMetricEntry[];
  latest: BodyMetricEntry | null;
  weightTrend: Array<{ recordedAt: string; value: number }>;
};

export type CreateBodyMetricInput = {
  weight?: number;
  measurements?: Record<string, number>;
  note?: string | null;
  recordedAt?: string;
};

// ---------------------------------------------------------------------------
// Cardio (mirrors backend serialized shapes — see cardio.service.ts /
// cardio.routes.ts). Distance is canonical in meters; speed in km/h.
// ---------------------------------------------------------------------------

/** The 9 cardio activities, matching the backend CardioActivity prisma enum. */
export type CardioActivity =
  | "TREADMILL"
  | "BIKE"
  | "ROWER"
  | "STAIR"
  | "ELLIPTICAL"
  | "OUTDOOR_RUN"
  | "OUTDOOR_WALK"
  | "OUTDOOR_CYCLE"
  | "OTHER";

/** Serialized cardio session (cardio.service.ts `serializeSession`). */
export type CardioSession = {
  id: string;
  activity: CardioActivity;
  performedAt: string;
  durationSeconds: number;
  distanceMeters: number | null;
  avgSpeedKmh: number | null;
  inclinePct: number | null;
  resistanceLevel: number | null;
  avgWatts: number | null;
  avgHr: number | null;
  maxHr: number | null;
  rpe: number | null;
  caloriesEstimated: number | null;
  caloriesManual: number | null;
  /** Display calories: manual machine value when present, else the estimate. */
  calories: number | null;
  bodyweightKgAt: number | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

export type CardioMetrics = {
  minutes: number;
  sessions: number;
  distanceMeters: number;
  calories: number;
  weightEquivalentKg: number;
};

export type CardioSummary = CardioMetrics & {
  deltas: CardioMetrics;
};

export type CardioCalendarDay = {
  date: string;
  sessions: number;
  minutes: number;
  calories: number;
};

export type CardioCalendar = {
  from: string;
  to: string;
  days: CardioCalendarDay[];
};

export type CardioProgression = {
  activity: CardioActivity | null;
  distanceTrend: Array<{ date: string; value: number }>;
  paceTrend: Array<{ date: string; value: number }>;
  sustainedLoad: {
    baseline: { label: string; value: number } | null;
    current: { label: string; value: number } | null;
  };
  weeklyMinutes: Array<{ weekStart: string; minutes: number; goal: number }>;
  weeklyGoal: number;
};

export type CardioPeriod = "week" | "month" | "all";

/**
 * Create/update body for a cardio session. Distance is sent in the chosen unit
 * (`distance` + `distanceUnit`) and converted to canonical meters server-side.
 */
export type CardioSessionInput = {
  activity: CardioActivity;
  performedAt: string;
  durationSeconds: number;
  distance?: number;
  distanceUnit?: "km" | "mi" | "m";
  inclinePct?: number;
  resistanceLevel?: number;
  avgSpeedKmh?: number;
  avgWatts?: number;
  avgHr?: number;
  maxHr?: number;
  rpe?: number;
  caloriesManual?: number;
  notes?: string;
};

export type ExerciseProgressExposure = {
  workoutId: string;
  workoutTitle: string;
  completedAt: string;
  wasPlanned: boolean;
  volume: number;
  bestSetLabel: string;
  estimatedOneRepMax: number | null;
  personalRecordCount: number;
};

export type ExerciseProgressSummary = {
  totalSessions: number;
  totalVolume: number;
  bestSetLabel: string | null;
  bestEstimatedOneRepMax: number | null;
  lastPerformed: string | null;
  personalRecordCount: number;
};

export type ExerciseProgressDetail = {
  exercise: Exercise;
  summary: ExerciseProgressSummary;
  recentSessions: ExerciseProgressExposure[];
  volumeHistory: Array<{
    completedAt: string;
    value: number;
  }>;
  estimatedOneRepMaxHistory: Array<{
    completedAt: string;
    value: number | null;
  }>;
  personalRecordTimeline: Array<{
    completedAt: string;
    workoutId: string;
    workoutTitle: string;
    count: number;
  }>;
};

export type ProfileShowcase = {
  featuredFamilies: ChallengeFamily[];
  unlockedTitles: ChallengeRewardItem[];
  unlockedBadges: ChallengeRewardItem[];
  recentUnlocks: ChallengeUnlock[];
};

export type ProfileView = {
  user: User;
  showcase: ProfileShowcase;
  editable: boolean;
  isFollowing?: boolean;
  copyablePrograms?: CopyableProgram[];
};

export type CopyableProgram = {
  id: string;
  name: string;
  goal: string;
  description: string | null;
  weekCount: number;
};

export type AppNotification = {
  id: string;
  type: string;
  title: string;
  body: string | null;
  payload: Record<string, unknown> | null;
  read: boolean;
  createdAt: string;
};

export type WorkoutInvite = {
  id: string;
  fromUserId: string;
  toUserId: string;
  workoutTitle: string;
  exercises: Array<{
    exerciseId: string;
    exerciseName: string;
    sets: number;
    repMin: number;
    repMax: number;
  }>;
  status: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED";
  expiresAt: string;
  createdAt: string;
  fromUser?: { id: string; displayName: string };
};

export type WorkoutComparison = {
  mySession: { completedAt: string | null };
  mateSession: { completedAt: string | null; displayName: string };
  exercises: Array<{
    exerciseName: string;
    myVolumeChange: number | null;
    mateVolumeChange: number | null;
    myE1rmChange: number | null;
    mateE1rmChange: number | null;
  }>;
};

// ===========================================================================
// Supplements (backend: supplement.service.ts + supplements.routes.ts)
// ===========================================================================

/** Physical form of a supplement (Prisma `SuppForm`). */
export type SuppForm = "TABLET" | "CAPSULE" | "POWDER" | "LIQUID" | "INJECTION" | "OTHER";

/** Time-of-day slot a dose is scheduled into (Prisma `SuppSlot`). */
export type SuppSlot =
  | "MORNING"
  | "MIDDAY"
  | "EVENING"
  | "BEDTIME"
  | "PRE_WORKOUT"
  | "INTRA_WORKOUT"
  | "POST_WORKOUT"
  | "CUSTOM";

/** Recurrence frequency of a schedule (Prisma `SuppFreq`). */
export type SuppFreq = "DAILY" | "WEEKLY" | "EVERY_N_DAYS" | "AS_NEEDED";

/** Logged status of an intake (Prisma `IntakeStatus`). */
export type IntakeStatus = "TAKEN" | "SKIPPED" | "SNOOZED" | "MISSED";

/** Phase kind within a cycle (Prisma `CyclePhaseKind`). */
export type CyclePhaseKind =
  | "ON"
  | "OFF"
  | "LOAD"
  | "MAINTAIN"
  | "PCT"
  | "BRIDGE"
  | "BLAST"
  | "CRUISE"
  | "TAPER_STEP";

/** A supplement in the user's catalog (`serializeSupplement`). */
export type Supplement = {
  id: string;
  name: string;
  brand: string | null;
  form: SuppForm;
  defaultUnit: string;
  servingSize: number | null;
  servingUnit: string | null;
  servingsPerContainer: number | null;
  tags: string[];
  color: string | null;
  icon: string | null;
  notes: string | null;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
};

/** A member entry within a stack (`serializeStack` members). */
export type SupplementStackMember = {
  id: string;
  supplementId: string;
  sortOrder: number;
};

/** A named group of supplements taken together (`serializeStack`). */
export type SupplementStack = {
  id: string;
  name: string;
  goal: string | null;
  color: string | null;
  paused: boolean;
  createdAt: string;
  updatedAt: string;
  members: SupplementStackMember[];
};

/** A recurrence/cycle binding for a supplement dose (`serializeSchedule`). */
export type SupplementSchedule = {
  id: string;
  supplementId: string;
  stackId: string | null;
  cycleId: string | null;
  cyclePhaseId: string | null;
  doseAmount: number;
  doseUnit: string;
  withFood: string | null;
  slot: SuppSlot;
  clockTime: string | null;
  freq: SuppFreq;
  interval: number;
  byWeekday: number[];
  timesPerDay: number;
  isPrn: boolean;
  startDate: string;
  endDate: string | null;
};

/** A single phase within a cycle (`serializeCycle` phases). */
export type SupplementCyclePhase = {
  id: string;
  order: number;
  kind: CyclePhaseKind;
  durationDays: number;
  startDelayDays: number;
  label: string | null;
};

/** A multi-phase on/off cycle (`serializeCycle`). */
export type SupplementCycle = {
  id: string;
  name: string;
  type: string;
  startDate: string;
  repeats: boolean;
  createdAt: string;
  updatedAt: string;
  phases: SupplementCyclePhase[];
};

/** Inventory/run-out state for a supplement (`serializeInventory`). */
export type SupplementInventory = {
  id: string;
  supplementId: string;
  servingsRemaining: number;
  containerSize: number | null;
  autoDecrement: boolean;
  lowStockThresholdServings: number;
  reorderUrl: string | null;
  remindBeforeDays: number;
  updatedAt: string;
};

/** A logged intake record returned by `logIntake`. */
export type SupplementIntake = {
  id: string;
  supplementId: string;
  scheduleId: string | null;
  status: IntakeStatus;
  scheduledFor: string;
  doseAmount: number;
  doseUnit: string;
  source: string;
};

/** Inventory chip embedded on a Today item (`buildInventoryChip`). */
export type SupplementInventoryChip = {
  servingsRemaining: number;
  lowStockThresholdServings: number;
  estimatedRunOutDays: number | null;
  lowStock: boolean;
  reorderUrl: string | null;
};

/** Cycle position embedded on a Today item (`cyclePosition`, serialized). */
export type SupplementCyclePositionToday = {
  kind: string | null;
  dayInPhase: number | null;
  phaseLength: number | null;
  nextTransitionDate: string | null;
};

/** A single checklist row in the Today response (`TodayChecklistItem`). */
export type SupplementTodayItem = {
  scheduleId: string;
  supplement: {
    id: string;
    name: string;
    form: SuppForm;
    color: string | null;
    icon: string | null;
    tags: string[];
  };
  doseAmount: number;
  doseUnit: string;
  withFood: string | null;
  slot: SuppSlot;
  clockTime: string | null;
  stackId: string | null;
  cyclePosition: SupplementCyclePositionToday | null;
  inventory: SupplementInventoryChip | null;
  status: IntakeStatus | null;
};

/** Slot group within the Today response (`TodaySlotGroup`). */
export type SupplementTodaySlotGroup = {
  slot: SuppSlot;
  items: SupplementTodayItem[];
};

/** Stack header within the Today response (`TodayStackGroup`). */
export type SupplementTodayStackGroup = {
  stackId: string;
  name: string;
  paused: boolean;
  scheduleIds: string[];
};

/** The `GET /supplements/today` response (`TodayResult`). */
export type SupplementToday = {
  date: string;
  slots: SupplementTodaySlotGroup[];
  asNeeded: SupplementTodayItem[];
  stacks: SupplementTodayStackGroup[];
  adherence: { taken: number; due: number };
};

/** The `GET /supplements/adherence` response (`getAdherence`). */
export type SupplementAdherence = {
  windowDays: number;
  /** taken/scheduled over the window, or null when nothing was scheduled. */
  overall: number | null;
  /** Per-supplement adherence keyed by supplement id (null when none scheduled). */
  perSupplement: Record<string, number | null>;
  streakDays: number;
};

/** A single calendar day bucket (`getCalendar` days). */
export type SupplementCalendarDay = {
  date: string;
  scheduledCount: number;
  takenCount: number;
  pct: number;
  isOffDay: boolean;
};

/** The `GET /supplements/calendar` response (`getCalendar`). */
export type SupplementCalendar = {
  from: string;
  to: string;
  days: SupplementCalendarDay[];
};

/** Result returned by `logIntake` / per-item in `logStackIntake`. */
export type SupplementLogIntakeResult = {
  intake: SupplementIntake;
  inventory: SupplementInventoryChip | null;
};

/** Result returned by `POST /supplements/stacks/:id/intake`. */
export type SupplementStackIntakeResult = {
  stackId: string;
  logged: SupplementLogIntakeResult[];
};

/** Adherence query windows accepted by the API. */
export type SupplementAdherenceWindow = 7 | 30 | 90;

// --- Input bodies (mirror the Zod schemas in supplements.routes.ts) ---

export type CreateSupplementInput = {
  name: string;
  brand?: string | null;
  form: SuppForm;
  defaultUnit: string;
  servingSize?: number | null;
  servingUnit?: string | null;
  servingsPerContainer?: number | null;
  tags?: string[];
  color?: string | null;
  icon?: string | null;
  notes?: string | null;
};

export type UpdateSupplementInput = Partial<CreateSupplementInput> & {
  archived?: boolean;
};

export type CreateStackInput = {
  name: string;
  goal?: string | null;
  color?: string | null;
};

export type UpdateStackInput = Partial<CreateStackInput> & {
  paused?: boolean;
};

export type AddStackMemberInput = {
  supplementId: string;
  sortOrder?: number;
};

export type CyclePhaseInput = {
  order: number;
  kind: CyclePhaseKind;
  durationDays: number;
  startDelayDays?: number;
  label?: string | null;
};

export type CreateCycleInput = {
  name: string;
  type: string;
  /** ISO 8601 datetime string. */
  startDate: string;
  repeats?: boolean;
  phases: CyclePhaseInput[];
};

export type UpdateCycleInput = {
  name?: string;
  type?: string;
  startDate?: string;
  repeats?: boolean;
  phases?: CyclePhaseInput[];
};

export type CreateScheduleInput = {
  supplementId: string;
  stackId?: string | null;
  cycleId?: string | null;
  cyclePhaseId?: string | null;
  doseAmount: number;
  doseUnit: string;
  withFood?: string | null;
  slot: SuppSlot;
  clockTime?: string | null;
  freq: SuppFreq;
  interval?: number;
  byWeekday?: number[];
  timesPerDay?: number;
  isPrn?: boolean;
  prnMaxPerDay?: number | null;
  prnMinIntervalHrs?: number | null;
  /** ISO 8601 datetime string. */
  startDate: string;
  endDate?: string | null;
  reminderEnabled?: boolean;
  reminderWindowMins?: number;
};

export type UpdateScheduleInput = Partial<Omit<CreateScheduleInput, "supplementId">>;

export type UpsertInventoryInput = {
  servingsRemaining: number;
  containerSize?: number | null;
  autoDecrement?: boolean;
  lowStockThresholdServings?: number;
  reorderUrl?: string | null;
  remindBeforeDays?: number;
};

/** Body for `POST /supplements/intake`. */
export type LogSupplementIntakeInput = {
  supplementId?: string;
  scheduleId?: string;
  status: IntakeStatus;
  /** ISO 8601 datetime string. */
  scheduledFor: string;
  doseAmount?: number;
  doseUnit?: string;
  source?: "manual" | "reminder" | "stack_bulk";
  stackId?: string | null;
};

/** Body for `POST /supplements/stacks/:id/intake`. */
export type LogStackIntakeInput = {
  status: IntakeStatus;
  /** YYYY-MM-DD; defaults to today server-side. */
  date?: string;
};
