export type ApiSuccess<T> = {
  success: true;
  data: T;
};

export type ApiError = {
  success: false;
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

export type ApiResponse<T> = ApiSuccess<T> | ApiError;

export type User = {
  id: string;
  email: string;
  displayName: string;
  preferredUnit: "kg" | "lb";
  xpTotal: number;
  level: number;
  selectedTitleKey?: string | null;
  selectedTitleLabel?: string | null;
  selectedBadgeKey?: string | null;
  selectedBadgeLabel?: string | null;
  avatarConfig: Record<string, unknown> | null;
};

export type SocialUser = {
  id: string;
  email: string;
  displayName: string;
  level: number;
  xpTotal: number;
  selectedTitleLabel?: string | null;
  selectedBadgeLabel?: string | null;
  isFollowing: boolean;
};

export type Exercise = {
  id: string;
  name: string;
  exerciseCategory: "STRENGTH" | "CARDIO";
  equipmentType: string;
  machineType: string | null;
  attachment: string | null;
  loadType:
    | "BODYWEIGHT"
    | "ASSISTED_BODYWEIGHT"
    | "EXTERNAL"
    | "FIXED_WEIGHT"
    | "PLATE_TOTAL"
    | "STACK"
    | "CABLE_STACK";
  unitMode: "kg" | "lb";
  primaryMuscles: string[];
  secondaryMuscles: string[];
  isSystem: boolean;
};

export type ExerciseSubstitutes = {
  sourceExercise: Exercise;
  equivalents: Exercise[];
  alternatives: Exercise[];
};

export type LoadType = Exercise["loadType"];

export type ExerciseCategory = Exercise["exerciseCategory"];

export type TrackingMode =
  | "ABSOLUTE_WEIGHT"
  | "PLATES_PER_SIDE"
  | "BODYWEIGHT_ONLY"
  | "BODYWEIGHT_PLUS_LOAD"
  | "BAND_LEVEL"
  | "PER_SIDE_LOAD"
  | "CARDIO";

export type WorkoutSetType =
  | "NORMAL"
  | "WARMUP"
  | "AMRAP"
  | "DROP"
  | "CLUSTER"
  | "SUPERSET"
  | "CARDIO";

export type WorkoutSetTrackingData = {
  unilateral?: boolean | null;
  leftWeight?: number | null;
  rightWeight?: number | null;
  leftReps?: number | null;
  rightReps?: number | null;
  leftRpe?: number | null;
  rightRpe?: number | null;
  plateCount?: number | null;
  plateWeight?: number | null;
  barWeight?: number | null;
  externalLoad?: number | null;
  bandLevel?: string | null;
  perSideLoad?: number | null;
  durationSeconds?: number | null;
  distance?: number | null;
  distanceUnit?: string | null;
  incline?: number | null;
  resistance?: number | null;
  speed?: number | null;
  clusterSize?: number | null;
  clusterPattern?: string | null;
  generatedFromSetNumber?: number | null;
  dropPhase?: number | null;
  dropPercent?: number | null;
  dropGroupId?: string | null;
  autoGenerated?: boolean | null;
};

export type ProgramExercise = {
  id: string;
  exerciseId: string;
  orderIndex: number;
  sets: number;
  repMin: number;
  repMax: number;
  restSeconds: number;
  startWeight: number | null;
  increment: number;
  deloadFactor: number;
  targetRpe: number | null;
  loadTypeOverride: Exercise["loadType"] | null;
  trackingMode: TrackingMode | null;
  defaultTrackingData: WorkoutSetTrackingData | null;
  machineOverride: string | null;
  attachmentOverride: string | null;
  unilateral: boolean;
  notes: string | null;
  exercise: Exercise;
};

export type ProgramWorkout = {
  id: string;
  dayLabel: string;
  title: string;
  orderIndex: number;
  estimatedMinutes: number;
  xpReward: number;
  exercises: ProgramExercise[];
};

export type ProgramWeek = {
  id: string;
  weekNumber: number;
  label: string;
  isDeload: boolean;
  workouts: ProgramWorkout[];
};

export type Program = {
  id: string;
  isSystem: boolean;
  name: string;
  goal: string;
  description: string | null;
  status: "ACTIVE" | "PAUSED" | "COMPLETED" | "ARCHIVED";
  currentWeek: number;
  adherenceStreak: number;
  weeks: ProgramWeek[];
};

export type ProgramDifficulty = "Beginner" | "Intermediate" | "Advanced";
export type ProgramGoal =
  | "Strength"
  | "Hypertrophy"
  | "General Fitness"
  | "Powerlifting";

export type TemplateExercise = {
  id: string;
  exerciseId: string;
  orderIndex: number;
  sets: number;
  repMin: number;
  repMax: number;
  restSeconds: number;
  startWeight: number | null;
  loadTypeOverride: LoadType | null;
  trackingMode: TrackingMode | null;
  defaultTrackingData: WorkoutSetTrackingData | null;
  machineOverride: string | null;
  attachmentOverride: string | null;
  unilateral: boolean;
  notes: string | null;
  exercise: Exercise;
};

export type WorkoutTemplate = {
  id: string;
  isSystem: boolean;
  name: string;
  description: string | null;
  exercises: TemplateExercise[];
};

export type DraftExercise = {
  exerciseId: string;
  exerciseName?: string;
  exerciseCategory?: ExerciseCategory;
  sets: number;
  repMin: number;
  repMax: number;
  restSeconds?: number;
  startWeight?: number | null;
  increment?: number;
  deloadFactor?: number;
  targetRpe?: number | null;
  loadTypeOverride?: LoadType | null;
  trackingMode?: TrackingMode | null;
  defaultTrackingData?: WorkoutSetTrackingData | null;
  machineOverride?: string | null;
  attachmentOverride?: string | null;
  unilateral?: boolean;
  notes?: string | null;
};

export type DraftTemplateDay = {
  templateId?: string;
  dayLabel: string;
  title: string;
  description?: string;
  estimatedMinutes?: number;
  exercises: DraftExercise[];
};

export type CreateProgramInput = {
  name: string;
  goal: ProgramGoal;
  description?: string;
  durationWeeks: number;
  daysPerWeek: number;
  days: DraftTemplateDay[];
};

export type ProgramDraft = {
  name: string;
  goal: ProgramGoal;
  description: string;
  durationWeeks: number;
  daysPerWeek: number;
  difficulty: ProgramDifficulty;
  days: DraftTemplateDay[];
};

export type TemplateDraft = {
  name: string;
  description: string;
  estimatedMinutes: number;
  exercises: DraftExercise[];
};

export type ProgressionRecommendation = {
  state: "START" | "HOLD" | "INCREASE" | "DELOAD";
  weight: number | null;
  reason: string;
};

export type ActiveProgram = Program & {
  currentWeek: ProgramWeek | undefined;
  currentWeekTotal: number;
  currentWeekCompleted: number;
  currentWeekSkipped: number;
  currentWeekCompletion: number;
  completedWorkoutIds: string[];
  skippedWorkoutIds: string[];
  graceHours: number;
  recommendations: Record<string, ProgressionRecommendation>;
};

export type WorkoutSession = {
  id: string;
  title: string;
  entryType: "PROGRAM" | "TEMPLATE" | "QUICK";
  status: "DRAFT" | "IN_PROGRESS" | "COMPLETED";
  wasPlanned: boolean;
  totalXp: number;
  notes: string | null;
  savedDraft: WorkoutDraft | null;
  originDraft: WorkoutDraft | null;
  startedAt: string;
  pausedAt: string | null;
  accumulatedPauseSeconds: number;
  totalDurationSeconds: number | null;
  completedAt: string | null;
  programWorkoutId: string | null;
  templateId: string | null;
};

export type WorkoutSetRecord = {
  id: string;
  setNumber: number;
  weight: number | null;
  reps: number;
  rpe: number | null;
  setType: WorkoutSetType;
  trackingData: WorkoutSetTrackingData | null;
  isWorkingSet: boolean;
  isPersonalRecord: boolean;
};

export type WorkoutExerciseRecord = {
  id: string;
  exerciseId: string | null;
  exerciseName: string;
  exerciseCategory: ExerciseCategory;
  equipmentType: string;
  machineType: string | null;
  attachment: string | null;
  loadType: Exercise["loadType"];
  trackingMode: TrackingMode | null;
  defaultTrackingData: WorkoutSetTrackingData | null;
  unitMode: "kg" | "lb";
  unilateral: boolean;
  orderIndex: number;
  notes: string | null;
  prescribedSetCount: number | null;
  repMin: number | null;
  repMax: number | null;
  suggestedWeight: number | null;
  sourceProgramExerciseId: string | null;
  substitutedFromExerciseId: string | null;
  substitutedFromExerciseName: string | null;
  substitutionMode: "EQUIVALENT" | "ALTERNATE" | null;
  countsForProgression: boolean;
  supersetGroupId: string | null;
  supersetPosition: number | null;
  sets: WorkoutSetRecord[];
};

export type WorkoutExerciseReview = {
  workoutExerciseId: string;
  volume: number;
  bestSetLabel: string;
  estimatedOneRepMax: number | null;
  personalRecordSets: number;
  previousVolume: number | null;
  previousBestSetLabel: string | null;
  previousEstimatedOneRepMax: number | null;
  volumeChange: number | null;
  oneRepMaxChange: number | null;
};

export type WorkoutSessionDetail = WorkoutSession & {
  exercises: WorkoutExerciseRecord[];
  exerciseReviews: WorkoutExerciseReview[];
};

export type WorkoutDraftSet = {
  setNumber: number;
  weight: number | null;
  reps: number;
  rpe: number | null;
  completed?: boolean;
  setType?: WorkoutSetType;
  trackingData?: WorkoutSetTrackingData | null;
  isWorkingSet?: boolean;
};

export type WorkoutDraftExercise = {
  exerciseId: string | null;
  exerciseName: string;
  exerciseCategory: ExerciseCategory;
  equipmentType: string;
  machineType?: string | null;
  attachment?: string | null;
  loadType: Exercise["loadType"];
  trackingMode: TrackingMode;
  defaultTrackingData?: WorkoutSetTrackingData | null;
  unitMode: "kg" | "lb";
  unilateral?: boolean;
  notes?: string;
  prescribedSetCount?: number | null;
  repMin?: number | null;
  repMax?: number | null;
  suggestedWeight?: number | null;
  recommendationReason?: string | null;
  sourceProgramExerciseId?: string | null;
  substitutedFromExerciseId?: string | null;
  substitutedFromExerciseName?: string | null;
  substitutionMode?: "EQUIVALENT" | "ALTERNATE" | null;
  countsForProgression?: boolean;
  supersetGroupId?: string | null;
  supersetPosition?: number | null;
  sets: WorkoutDraftSet[];
};

export type CreateExerciseInput = {
  name: string;
  exerciseCategory?: ExerciseCategory;
  equipmentType: string;
  machineType?: string;
  attachment?: string;
  loadType: LoadType;
  primaryMuscles: string[];
  secondaryMuscles?: string[];
};

export type CreateTemplateInput = {
  name: string;
  description?: string;
  exercises: DraftExercise[];
};

export type WorkoutDraft = {
  title: string;
  notes?: string;
  exercises: WorkoutDraftExercise[];
};

export type LeaderboardEntry = {
  rank: number;
  userId: string;
  displayName: string;
  level: number;
  xp: number;
  selectedTitleLabel?: string | null;
  selectedBadgeLabel?: string | null;
};

export type Challenge = {
  id: string;
  key: string;
  title: string;
  description: string;
  joined: boolean;
  myScore: number;
  target: number | null;
  metric: "XP" | "WORKOUTS" | "PROGRAM_WEEKS" | "PRS";
  periodEnd: string;
};

export type ActivityEvent = {
  id: string;
  title: string;
  body: string | null;
  createdAt: string;
  type: string;
  user: Pick<User, "id" | "displayName" | "level">;
};

export type ChallengeCategory =
  | "CONSISTENCY"
  | "STRENGTH"
  | "PROGRESSION"
  | "PROGRAMS"
  | "SOCIAL";

export type ChallengeRank =
  | "ROOKIE"
  | "REGULAR"
  | "DEDICATED"
  | "SERIOUS"
  | "SAVAGE"
  | "TITAN"
  | "GOD";

export type ChallengeTierReward = {
  key: string;
  label: string;
};

export type ChallengeTier = {
  id: string;
  rank: ChallengeRank;
  threshold: number;
  xpReward: number;
  unlocked: boolean;
  unlockedAt: string | null;
  titleRewardKey: string | null;
  titleRewardLabel: string | null;
  badgeRewardKey: string | null;
  badgeRewardLabel: string | null;
};

export type ChallengeFamily = {
  id: string;
  key: string;
  category: ChallengeCategory;
  categoryLabel: string;
  iconKey: string;
  title: string;
  description: string;
  progress: number;
  currentRank: ChallengeRank | null;
  nextTier:
    | {
        id: string;
        rank: ChallengeRank;
        threshold: number;
        xpReward: number;
        remaining: number;
        titleRewardKey: string | null;
        titleRewardLabel: string | null;
        badgeRewardKey: string | null;
        badgeRewardLabel: string | null;
      }
    | null;
  tiers: ChallengeTier[];
};

export type ChallengeCategorySection = {
  key: ChallengeCategory;
  label: string;
  families: ChallengeFamily[];
};

export type ChallengeUnlock = {
  familyId: string;
  familyKey: string;
  familyTitle: string;
  iconKey: string;
  rank: ChallengeRank;
  threshold: number;
  xpReward: number;
  unlockedAt: string;
  titleRewardKey: string | null;
  titleRewardLabel: string | null;
  badgeRewardKey: string | null;
  badgeRewardLabel: string | null;
};

export type ChallengeRewardItem = {
  key: string;
  label: string;
  familyKey: string;
  familyTitle: string;
  rank: ChallengeRank;
  unlockedAt: string;
};

export type ChallengeLibrary = {
  categories: ChallengeCategorySection[];
  families: ChallengeFamily[];
  summary: {
    unlockedTierCount: number;
    totalTierCount: number;
    unlockedFamilyCount: number;
    totalFamilyCount: number;
    recentUnlocks: ChallengeUnlock[];
    closestNext: ChallengeFamily[];
    unlockedTitles: ChallengeRewardItem[];
    unlockedBadges: ChallengeRewardItem[];
  };
};

export type ProgressWeeklyExercise = {
  exerciseId: string;
  exerciseName: string;
  volume: number;
  sessions: number;
};

export type ProgressWeeklyMuscle = {
  muscle: string;
  volume: number;
};

export type ProgressWeeklySummary = {
  startDate: string;
  endDate: string;
  sessionsCompleted: number;
  plannedSessionsCompleted: number;
  unplannedSessionsCompleted: number;
  xpEarned: number;
  totalVolume: number;
  topExercises: ProgressWeeklyExercise[];
  topMuscleGroups: ProgressWeeklyMuscle[];
};

export type ProgressActiveProgramSummary = {
  programId: string;
  name: string;
  currentWeek: number;
  completed: number;
  total: number;
  completion: number;
} | null;

export type ProgressRecentPr = {
  setId: string;
  workoutId: string;
  workoutTitle: string;
  exerciseId: string | null;
  exerciseName: string;
  bestSetLabel: string;
  estimatedOneRepMax: number | null;
  previousBest: number | null;
  improvement: number | null;
  completedAt: string;
};

export type ProgressExerciseTrend = {
  exerciseId: string;
  exerciseName: string;
  equipmentType: string;
  sessionCount: number;
  totalVolume: number;
  latestEstimatedOneRepMax: number | null;
  bestEstimatedOneRepMax: number | null;
  recentChange: number | null;
  lastPerformed: string;
  personalRecordCount: number;
};

export type ProgressChallengeSummary = {
  unlockedTierCount: number;
  totalTierCount: number;
  unlockedFamilyCount: number;
  totalFamilyCount: number;
  recentUnlocks: ChallengeUnlock[];
  closestNext: ChallengeFamily[];
};

export type ProgressOverview = {
  weeklySummary: ProgressWeeklySummary;
  activeProgramSummary: ProgressActiveProgramSummary;
  recentPrs: ProgressRecentPr[];
  exerciseTrends: ProgressExerciseTrend[];
  challengeSummary: ProgressChallengeSummary;
};

export type ExerciseProgressExposure = {
  workoutId: string;
  workoutTitle: string;
  completedAt: string;
  wasPlanned: boolean;
  volume: number;
  bestSetLabel: string;
  estimatedOneRepMax: number | null;
  personalRecordCount: number;
};

export type ExerciseProgressSummary = {
  totalSessions: number;
  totalVolume: number;
  bestSetLabel: string | null;
  bestEstimatedOneRepMax: number | null;
  lastPerformed: string | null;
  personalRecordCount: number;
};

export type ExerciseProgressDetail = {
  exercise: Exercise;
  summary: ExerciseProgressSummary;
  recentSessions: ExerciseProgressExposure[];
  volumeHistory: Array<{
    completedAt: string;
    value: number;
  }>;
  estimatedOneRepMaxHistory: Array<{
    completedAt: string;
    value: number | null;
  }>;
  personalRecordTimeline: Array<{
    completedAt: string;
    workoutId: string;
    workoutTitle: string;
    count: number;
  }>;
};

export type ProfileShowcase = {
  featuredFamilies: ChallengeFamily[];
  unlockedTitles: ChallengeRewardItem[];
  unlockedBadges: ChallengeRewardItem[];
  recentUnlocks: ChallengeUnlock[];
};

export type ProfileView = {
  user: User;
  showcase: ProfileShowcase;
  editable: boolean;
  isFollowing?: boolean;
};
