import { describe, expect, it } from "vitest";

import {
  calculatePlateLoadout,
  generateWarmupSets,
  warmupRampPercents,
} from "@/lib/workout-tracking";

describe("calculatePlateLoadout", () => {
  it("breaks a 100kg target on a 20kg bar into plates per side", () => {
    const result = calculatePlateLoadout(100, 20, undefined, "kg");

    // 40kg per side -> 25 + 15
    expect(result.perSide).toEqual([
      { weight: 25, count: 1 },
      { weight: 15, count: 1 },
    ]);
    expect(result.achievableWeight).toBe(100);
    expect(result.leftoverPerSide).toBe(0);
  });

  it("stacks multiple plates of the same denomination", () => {
    const result = calculatePlateLoadout(160, 20, undefined, "kg");

    // 70kg per side -> 25 + 25 + 20
    expect(result.perSide).toEqual([
      { weight: 25, count: 2 },
      { weight: 20, count: 1 },
    ]);
    expect(result.achievableWeight).toBe(160);
  });

  it("reports leftover when the target is not achievable with the inventory", () => {
    // Only 25s available: 30kg/side target leaves 5kg unmatched.
    const result = calculatePlateLoadout(80, 20, [25], "kg");

    expect(result.perSide).toEqual([{ weight: 25, count: 1 }]);
    expect(result.achievableWeight).toBe(70);
    expect(result.leftoverPerSide).toBe(5);
  });

  it("returns just the bar when the target is at or below bar weight", () => {
    const result = calculatePlateLoadout(20, 20, undefined, "kg");

    expect(result.perSide).toEqual([]);
    expect(result.achievableWeight).toBe(20);
    expect(result.leftoverPerSide).toBe(0);
  });

  it("uses pound denominations when unit is lb", () => {
    const result = calculatePlateLoadout(225, 45, undefined, "lb");

    // 90lb per side -> 45 + 45
    expect(result.perSide).toEqual([{ weight: 45, count: 2 }]);
    expect(result.achievableWeight).toBe(225);
  });
});

describe("generateWarmupSets", () => {
  it("creates one ramped warmup set per percentage", () => {
    const sets = generateWarmupSets(100);

    expect(sets).toHaveLength(warmupRampPercents.length);
    expect(sets.map((set) => set.weight)).toEqual([40, 60, 80]);
    expect(sets.every((set) => set.setType === "WARMUP")).toBe(true);
    expect(sets.every((set) => set.isWorkingSet === false)).toBe(true);
    expect(sets.every((set) => set.trackingData?.autoGenerated === true)).toBe(true);
  });

  it("rounds to the nearest plate increment", () => {
    const sets = generateWarmupSets(102.5, { roundTo: 2.5 });

    // 40% of 102.5 = 41 -> rounds to 40
    expect(sets[0].weight).toBe(40);
  });

  it("descends reps as load increases", () => {
    const sets = generateWarmupSets(100, { reps: 8 });
    const reps = sets.map((set) => set.reps);

    expect(reps[0]).toBeGreaterThanOrEqual(reps[reps.length - 1]);
    expect(Math.min(...reps)).toBeGreaterThanOrEqual(2);
  });
});
