"use client";

import { Reorder, useDragControls } from "framer-motion";
import {
  Flame,
  GripVertical,
  History,
  Link2,
  MoreHorizontal,
  Plus,
  Settings2,
  Shuffle,
  Trash2,
  Unlink,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { CoachChip } from "@/components/ui/coach-chip";
import { useKeypad } from "@/components/ui/keypad-context";
import { cn } from "@/lib/utils";

import { SetGrid } from "./set-grid";
import { useWorkoutEditor, type ExerciseSheetKind } from "./workout-editor-context";

const REMOVE_CONFIRM_MS = 3000;

/** One vertically stacked exercise card: header, coach chip, set grid, actions. */
export const ExerciseCard = ({ exerciseIndex }: { exerciseIndex: number }) => {
  const {
    addDropSet,
    addSet,
    applySuggestedWeight,
    draft,
    generateWarmups,
    openExerciseSheet,
    registerCardElement,
    removeExercise,
    setExerciseUnilateral,
    supersetHueFor,
    unpairSuperset,
  } = useWorkoutEditor();

  const { closeKeypad } = useKeypad();
  const dragControls = useDragControls();
  const [actionsOpen, setActionsOpen] = useState(false);
  const [removeArmed, setRemoveArmed] = useState(false);
  const removeTimerRef = useRef<number | null>(null);

  useEffect(
    () => () => {
      if (removeTimerRef.current) {
        window.clearTimeout(removeTimerRef.current);
      }
    },
    [],
  );

  const exercise = draft.exercises[exerciseIndex];

  if (!exercise) {
    return null;
  }

  const formative = draft.formativeWeek === true;
  const hasSuggestion =
    typeof exercise.suggestedWeight === "number" || Boolean(exercise.recommendationReason);
  const isCardio = exercise.exerciseCategory === "CARDIO";
  const dropParents = exercise.sets.filter(
    (set) => set.setType === "DROP" && set.trackingData?.autoGenerated !== true,
  );
  const lastDropParent = dropParents.at(-1) ?? null;
  const canGenerateWarmups = exercise.trackingMode === "ABSOLUTE_WEIGHT" && !isCardio;
  const exerciseIsUnilateral =
    exercise.unilateral === true ||
    exercise.sets.some((set) => set.trackingData?.unilateral === true);
  const supersetHue = exercise.supersetGroupId ? supersetHueFor(exercise.supersetGroupId) : null;
  const supersetSize = exercise.supersetGroupId
    ? draft.exercises.filter(
        (candidate) => candidate.supersetGroupId === exercise.supersetGroupId,
      ).length
    : 0;

  // Modal sheets sit under the keypad's z-index; close (and commit) it first.
  const openSheet = (kind: ExerciseSheetKind) => {
    closeKeypad();
    openExerciseSheet(kind, exerciseIndex);
  };

  const handleRemove = () => {
    if (!removeArmed) {
      setRemoveArmed(true);
      removeTimerRef.current = window.setTimeout(() => setRemoveArmed(false), REMOVE_CONFIRM_MS);
      return;
    }

    if (removeTimerRef.current) {
      window.clearTimeout(removeTimerRef.current);
    }
    removeExercise(exerciseIndex);
  };

  return (
    <Reorder.Item
      as="section"
      value={exercise.clientKey ?? `${exercise.exerciseName}-${exerciseIndex}`}
      dragListener={false}
      dragControls={dragControls}
      whileDrag={{ scale: 1.015, zIndex: 25, boxShadow: "0 10px 30px hsl(var(--shadow-active) / 0.45)" }}
      ref={(element: HTMLElement | null) => registerCardElement(exerciseIndex, element)}
      className={cn(
        "surface-card relative scroll-mt-28 p-3",
        supersetHue !== null && "border-l-4",
      )}
      style={
        supersetHue !== null
          ? { borderLeftColor: `hsl(${supersetHue} 70% 55%)` }
          : undefined
      }
    >
      <div className="flex items-start gap-1.5">
        <button
          aria-label={`Drag to reorder ${exercise.exerciseName}`}
          className="-ml-1.5 flex h-11 w-8 shrink-0 cursor-grab touch-none items-center justify-center rounded-md text-ink-subtle active:cursor-grabbing active:text-ink"
          type="button"
          onPointerDown={(event) => {
            closeKeypad();
            dragControls.start(event);
          }}
        >
          <GripVertical className="h-4 w-4" />
        </button>
        <div className="min-w-0 flex-1">
          <h3 className="truncate font-display text-lg font-semibold tracking-editorial text-ink">
            {exercise.exerciseName}
          </h3>
          <p className="mt-0.5 truncate text-xs text-ink-muted">
            {exercise.equipmentType}
            {exercise.attachment ? ` • ${exercise.attachment}` : ""}
            {isCardio
              ? ` • ${Math.round(((exercise.defaultTrackingData?.durationSeconds as number | null | undefined) ?? 900) / 60)} min target`
              : exercise.repMin || exercise.repMax
                ? ` • ${exercise.repMin ?? "-"}–${exercise.repMax ?? "-"} reps`
                : ""}
            {exercise.supersetGroupId
              ? supersetSize >= 3
                ? ` • circuit · ${supersetSize}`
                : " • superset"
              : ""}
          </p>
          {exercise.substitutedFromExerciseName ? (
            <p className="mt-1 text-xs text-ink-muted">
              Replacing {exercise.substitutedFromExerciseName} •{" "}
              {exercise.countsForProgression ? "Counts for progression" : "Alternate only"}
            </p>
          ) : null}
        </div>
        <div className="flex shrink-0 items-center gap-1.5">
          {!isCardio ? (
            <Button
              aria-label={
                exerciseIsUnilateral
                  ? `Switch ${exercise.exerciseName} to bilateral`
                  : `Switch ${exercise.exerciseName} to unilateral (left/right)`
              }
              aria-pressed={exerciseIsUnilateral}
              className={cn(
                "h-8 px-2 text-[11px] font-semibold",
                exerciseIsUnilateral && "border-accent bg-accent-soft text-accent",
              )}
              size="sm"
              type="button"
              variant="outline"
              onClick={() => setExerciseUnilateral(exerciseIndex, !exerciseIsUnilateral)}
            >
              L/R
            </Button>
          ) : null}
          <Button
            aria-expanded={actionsOpen}
            aria-label={`Actions for ${exercise.exerciseName}`}
            size="icon"
            type="button"
            variant="ghost"
            onClick={() => setActionsOpen((current) => !current)}
          >
            <MoreHorizontal className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {actionsOpen ? (
        <div
          className={cn(
            "mt-2 grid gap-1.5",
            exercise.supersetGroupId ? "grid-cols-6" : "grid-cols-5",
          )}
        >
          <Button
            className="h-auto flex-col gap-1 py-2 text-[11px]"
            type="button"
            variant="outline"
            onClick={() => openSheet("history")}
          >
            <History className="h-4 w-4" />
            History
          </Button>
          <Button
            className="h-auto flex-col gap-1 py-2 text-[11px]"
            type="button"
            variant="outline"
            onClick={() => openSheet("swap")}
          >
            <Shuffle className="h-4 w-4" />
            Swap
          </Button>
          <Button
            className="h-auto flex-col gap-1 py-2 text-[11px]"
            type="button"
            variant="outline"
            onClick={() => openSheet("superset")}
          >
            <Link2 className="h-4 w-4" />
            Circuit
          </Button>
          {exercise.supersetGroupId ? (
            <Button
              className="h-auto flex-col gap-1 py-2 text-[11px]"
              type="button"
              variant="outline"
              onClick={() => unpairSuperset(exercise.supersetGroupId as string)}
            >
              <Unlink className="h-4 w-4" />
              {supersetSize >= 3 ? "Ungroup" : "Unpair"}
            </Button>
          ) : null}
          <Button
            className="h-auto flex-col gap-1 py-2 text-[11px]"
            type="button"
            variant="outline"
            onClick={() => openSheet("manage")}
          >
            <Settings2 className="h-4 w-4" />
            Manage
          </Button>
          <Button
            className={cn(
              "h-auto flex-col gap-1 py-2 text-[11px]",
              removeArmed ? "border-danger text-danger" : "text-danger",
            )}
            type="button"
            variant="outline"
            onClick={handleRemove}
          >
            <Trash2 className="h-4 w-4" />
            {removeArmed ? "Sure?" : "Remove"}
          </Button>
        </div>
      ) : null}

      {hasSuggestion ? (
        <CoachChip
          className="mt-2"
          formative={formative}
          valueLabel={
            typeof exercise.suggestedWeight === "number"
              ? `${exercise.suggestedWeight} ${exercise.unitMode}`
              : null
          }
          reason={exercise.recommendationReason ?? null}
          onApply={
            typeof exercise.suggestedWeight === "number"
              ? () => applySuggestedWeight(exerciseIndex)
              : undefined
          }
        />
      ) : null}

      {exercise.notes ? (
        <p className="mt-2 rounded-md bg-surface-sunken px-2 py-1.5 text-xs leading-5 text-ink-muted">
          {exercise.notes}
        </p>
      ) : null}

      <div className="mt-3">
        <SetGrid exerciseIndex={exerciseIndex} />
      </div>

      <div className="mt-2 flex items-center gap-2">
        <Button
          className="flex-1"
          size="sm"
          type="button"
          variant="outline"
          onClick={() => addSet(exerciseIndex)}
        >
          <Plus className="h-4 w-4" />
          Add set
        </Button>
        {lastDropParent ? (
          <Button
            size="sm"
            type="button"
            variant="outline"
            onClick={() => addDropSet(exerciseIndex, lastDropParent.setNumber)}
          >
            <Plus className="h-4 w-4" />
            Add drop
          </Button>
        ) : null}
        {canGenerateWarmups ? (
          <Button
            aria-label="Generate warm-up sets"
            size="sm"
            type="button"
            variant="ghost"
            onClick={() => generateWarmups(exerciseIndex)}
          >
            <Flame className="h-4 w-4" />
            Warm-ups
          </Button>
        ) : null}
      </div>
    </Reorder.Item>
  );
};
