"use client";

import { Minus, Plus, Trash2 } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { useKeypad } from "@/components/ui/keypad-context";
import { NumberField } from "@/components/ui/number-field";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import type { WorkoutSetType } from "@/lib/types";
import { isAutoGeneratedSet, strengthSetTypeOptions, toggleSetUnilateral } from "@/lib/workout-tracking";
import { cn } from "@/lib/utils";

import { useWorkoutEditor } from "./workout-editor-context";

const CHIP_LABELS: Partial<Record<WorkoutSetType, string>> = {
  WARMUP: "W",
  DROP: "D",
  AMRAP: "A",
  CLUSTER: "C",
  SUPERSET: "S",
};

const CHIP_CLASSES: Partial<Record<WorkoutSetType, string>> = {
  WARMUP: "border-[hsl(var(--warning)/0.45)] text-warning",
  DROP: "border-[hsl(var(--timer)/0.45)] text-timer",
  AMRAP: "border-[hsl(var(--accent)/0.45)] text-accent",
  CLUSTER: "border-[hsl(var(--coach)/0.45)] text-coach",
  SUPERSET: "border-[hsl(var(--success)/0.45)] text-success",
};

const parseClusterPattern = (pattern: string | null | undefined): number[] => {
  const segments = (pattern ?? "")
    .split(",")
    .map((segment) => Number(segment.trim()))
    .filter((segment) => Number.isFinite(segment) && segment > 0);

  return segments.length ? segments : [4, 4];
};

const parseTempo = (tempo: string | null | undefined): Array<number | null> => {
  const parts = (tempo ?? "").split("-").map((part) => Number(part.trim()));
  return [0, 1, 2, 3].map((index) =>
    Number.isFinite(parts[index]) ? Math.max(0, parts[index]) : null,
  );
};

const TEMPO_LABELS = ["Ecc", "Pause", "Con", "Pause"];

/**
 * The letter chip in a set row's first column. Tapping opens the set detail
 * sheet: type picker, cluster pattern stepper, tempo, per-set unilateral
 * toggle, and the delete-set action (the single delete mechanism).
 */
export const SetTypeChip = ({
  exerciseIndex,
  setIndex,
}: {
  exerciseIndex: number;
  setIndex: number;
}) => {
  const {
    changeSetType,
    draft,
    removeSet,
    showTempo,
    updateSet,
  } = useWorkoutEditor();
  const { closeKeypad } = useKeypad();
  const [open, setOpen] = useState(false);

  const exercise = draft.exercises[exerciseIndex];
  const set = exercise?.sets[setIndex];

  if (!exercise || !set) {
    return null;
  }

  const setType = set.setType ?? (exercise.exerciseCategory === "CARDIO" ? "CARDIO" : "NORMAL");
  const label = CHIP_LABELS[setType] ?? String(set.setNumber);
  const isCardio = exercise.exerciseCategory === "CARDIO";
  const trackingData = set.trackingData ?? exercise.defaultTrackingData ?? null;
  const isUnilateral = trackingData?.unilateral === true;
  const clusterSegments = parseClusterPattern(trackingData?.clusterPattern);
  const tempoParts = parseTempo(trackingData?.tempo);
  const manualSetCount = exercise.sets.filter((candidate) => !isAutoGeneratedSet(candidate)).length;
  const deleteDisabled = !isAutoGeneratedSet(set) && manualSetCount === 1;

  const writeClusterPattern = (segments: number[]) => {
    updateSet(exerciseIndex, setIndex, (candidate, current) => ({
      ...candidate,
      trackingData: {
        ...(candidate.trackingData ?? current.defaultTrackingData ?? {}),
        clusterPattern: segments.join(","),
      },
    }));
  };

  const writeTempo = (parts: Array<number | null>) => {
    const hasValue = parts.some((part) => part !== null);
    updateSet(exerciseIndex, setIndex, (candidate, current) => ({
      ...candidate,
      trackingData: {
        ...(candidate.trackingData ?? current.defaultTrackingData ?? {}),
        tempo: hasValue ? parts.map((part) => part ?? 0).join("-") : null,
      },
    }));
  };

  return (
    <>
      <button
        type="button"
        aria-label={`Set ${set.setNumber} options`}
        onClick={() => {
          closeKeypad();
          setOpen(true);
        }}
        className={cn(
          "num flex h-11 w-11 shrink-0 items-center justify-center rounded-full border text-sm font-semibold",
          "border-rule bg-surface-raised text-ink-muted",
          "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-accent",
          CHIP_CLASSES[setType],
        )}
      >
        {label}
      </button>

      {/* Non-modal so the numeric keypad (z-60) stays interactive for tempo fields. */}
      <Sheet modal={false} open={open} onOpenChange={setOpen}>
        <SheetContent
          side="bottom"
          onOpenAutoFocus={(event) => event.preventDefault()}
          onInteractOutside={(event) => {
            if ((event.target as HTMLElement | null)?.closest("[data-keypad]")) {
              event.preventDefault();
            }
          }}
          className="rounded-t-md p-0"
        >
          <SheetHeader className="px-6 pb-3 pt-4">
            <SheetTitle>Set {set.setNumber}</SheetTitle>
            <SheetDescription>
              {exercise.exerciseName}
              {trackingData?.autoGenerated
                ? ` • auto drop${trackingData.dropPhase ? ` ${trackingData.dropPhase}` : ""}`
                : ""}
            </SheetDescription>
          </SheetHeader>
          <div className="drawer-scroll-region max-h-[60vh] space-y-5 px-6 pb-6 pt-4">
            {!isCardio ? (
              <div className="space-y-2">
                <p className="eyebrow">Set type</p>
                <div className="grid grid-cols-3 gap-2">
                  {strengthSetTypeOptions.map((option) => {
                    const active = option.value === setType;
                    return (
                      <button
                        key={option.value}
                        type="button"
                        onClick={() => changeSetType(exerciseIndex, setIndex, option.value)}
                        className={cn(
                          "touch-target rounded-md border px-2 py-2 text-sm font-medium",
                          active
                            ? "border-rule-strong bg-surface-sunken text-ink"
                            : "border-rule text-ink-muted",
                        )}
                      >
                        {option.label}
                      </button>
                    );
                  })}
                </div>
              </div>
            ) : null}

            {setType === "CLUSTER" && !isCardio ? (
              <div className="space-y-2">
                <p className="eyebrow">Cluster pattern</p>
                <div className="flex flex-wrap items-center gap-2">
                  {clusterSegments.map((segment, index) => (
                    <div
                      key={`cluster-${index}`}
                      className="flex items-center gap-1 rounded-md border border-rule px-1 py-1"
                    >
                      <Button
                        aria-label={`Decrease segment ${index + 1}`}
                        className="h-8 w-8"
                        size="icon"
                        type="button"
                        variant="ghost"
                        onClick={() => {
                          const next = [...clusterSegments];
                          if (next[index] <= 1) {
                            if (next.length > 1) {
                              next.splice(index, 1);
                            }
                          } else {
                            next[index] -= 1;
                          }
                          writeClusterPattern(next);
                        }}
                      >
                        <Minus className="h-3.5 w-3.5" />
                      </Button>
                      <span className="num w-6 text-center text-sm font-semibold text-ink">
                        {segment}
                      </span>
                      <Button
                        aria-label={`Increase segment ${index + 1}`}
                        className="h-8 w-8"
                        size="icon"
                        type="button"
                        variant="ghost"
                        onClick={() => {
                          const next = [...clusterSegments];
                          next[index] += 1;
                          writeClusterPattern(next);
                        }}
                      >
                        <Plus className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  ))}
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    onClick={() =>
                      writeClusterPattern([...clusterSegments, clusterSegments.at(-1) ?? 4])
                    }
                  >
                    <Plus className="h-3.5 w-3.5" />
                    Segment
                  </Button>
                </div>
                <p className="text-xs text-ink-muted">
                  Total {clusterSegments.reduce((sum, segment) => sum + segment, 0)} reps in{" "}
                  {clusterSegments.length} mini-sets.
                </p>
              </div>
            ) : null}

            {showTempo && !isCardio ? (
              <div className="space-y-2">
                <p className="eyebrow">Tempo</p>
                <div className="grid grid-cols-4 gap-2">
                  {TEMPO_LABELS.map((tempoLabel, index) => (
                    <div key={`${tempoLabel}-${index}`} className="space-y-1">
                      <p className="text-center text-[10px] uppercase tracking-wide text-ink-muted">
                        {tempoLabel}
                      </p>
                      <NumberField
                        id={`tempo-${exerciseIndex}-${setIndex}-${index}`}
                        kind="generic"
                        label={`Tempo ${tempoLabel}`}
                        value={tempoParts[index]}
                        allowDecimal={false}
                        min={0}
                        max={20}
                        placeholder="-"
                        onCommit={(value) => {
                          const next = [...tempoParts];
                          next[index] = value;
                          writeTempo(next);
                        }}
                      />
                    </div>
                  ))}
                </div>
              </div>
            ) : null}

            {!isCardio ? (
              <Button
                className="w-full"
                type="button"
                variant={isUnilateral ? "default" : "outline"}
                onClick={() =>
                  updateSet(exerciseIndex, setIndex, (candidate, current) =>
                    toggleSetUnilateral(candidate, current),
                  )
                }
              >
                {isUnilateral ? "Log as bilateral set" : "Log left / right separately"}
              </Button>
            ) : null}

            <Button
              className="w-full text-danger"
              disabled={deleteDisabled}
              type="button"
              variant="outline"
              onClick={() => {
                removeSet(exerciseIndex, setIndex);
                setOpen(false);
              }}
            >
              <Trash2 className="h-4 w-4" />
              Delete set
            </Button>
          </div>
        </SheetContent>
      </Sheet>
    </>
  );
};
